parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
  - plugin:prettier/recommended

rules:
  react/react-in-jsx-scope: off
  "@typescript-eslint/explicit-module-boundary-types": 'off'
  "linebreak-style": 'off'
  "prettier/prettier":
    - error
    - endOfLine: 'auto'

overrides:
  - files:
    - "*.ts"
    - "*.tsx"
    rules:
      "@typescript-eslint/explicit-module-boundary-types":
        - error